### ISSUE TITLE
After Upgrade from 4.9.0 to 5.0.3 we get many "The supplied type Func<IX> does not implement IX."

### ISSUE THREAD

**Issue by mkurz01** [simpleinjector/SimpleInjector#858]
After an upgrade from 4.9.0 to 5.0.3 we observe many Exceptions like this one:

> The delegate that was registered for service type ICustomerDao using the UnregisteredTypeEventArgs.Register(Func&lt;object>) method threw an exception. The supplied type Func&lt;object> does not implement IMock&lt;ICustomerDao>.
> Parametername: serviceType

Stack trace:

```
SimpleInjector.ActivationException : The delegate that was registered for service type ICustomerDao using the UnregisteredTypeEventArgs.Register(Func<object>) method threw an exception. The supplied type Func<object> does not implement IMock<ICustomerDao>.
Parametername: serviceType
  ----> System.ArgumentException : The supplied type Func<object> does not implement IMock<ICustomerDao>.
Parametername: serviceType
   bei SimpleInjector.UnregisteredTypeEventArgs.UnregisteredTypeEventArgsCallHelper.GetInstance[TService](Func`1 instanceCreator)
   bei SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   bei SimpleInjector.InstanceProducer.GetInstance()
   bei SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   bei SimpleInjector.Container.GetInstance[TService]()
```

We use this extension method which worked fine with 4.9.0:
``` c#
public static void RegisterAutoDaoFromMockFactories(this Container container)
{
    container.ResolveUnregisteredType += (s, e) =>
    {
        Type type = e.UnregisteredServiceType;

        Type baseType = type.GetInterface(typeof(IBaseDao<,>).FullName);
        if (baseType == null || baseType.GetGenericTypeDefinition() != typeof(IBaseDao<,>))
        {
            return;
        }
        Type serviceType = typeof(IMock<>).MakeGenericType(type);
        e.Register(() => ((IMock<object>)container.GetInstance(serviceType)).Object);
    };
}
```

What is the reason and how can we fix this?

Regards,
Matthias

**Comment by dotnetjunkie** [comment]
Hi Matthias,

I'm uncertain what change is causing this issue. Can you provide me with a Minimal, Reproducible Example?

**Comment by mkurz01** [comment]
> I'm uncertain what change is causing this issue. Can you provide me with a Minimal, Reproducible Example?

I send you an invitation for the github repo with the Minimal, Reproducible Example. 

I'am looking forward for your response. :-)

**Comment by dotnetjunkie** [comment]
What's happening is that I pretty much screwed up here in the API design. Two things have changed in v5:

* `SingletonLifestyle` class was added, extending `Lifestyle`.
* Lifestyle.Singleton now exposes `SingletonLifestyle` instead of `Lifestyle`.
* `SingletonLifestyle` exposes a `CreateRegistration(Type, object, Container)` overload.

But `Lifestyle` already contained `CreateRegistration` overloads, of which you called the `CreateRegistration(Type, Func<object>, Container)` overload.

But C# overload resolution prefers an overload in the derived class before going to the base class. This means that in your case `SingletonLifestyle.CreateRegistration(Type, object, Container)` was selected, instead of `Lifestyle.CreateRegistration(Type, Func<object>, Container)`, even though it has the exact type match.

Calling `SingletonLifestyle.CreateRegistration(Type, object, Container)` throws an exception because the supplied `object` does not match the supplied `Type`.

I will create a new issue to fix this problem. In the meantime, you can use the following workaround. Instead of calling:

``` C#
var reg = Lifestyle.Singleton.CreateRegistration(type, createDelegate, container);
```

Do:

``` c#
var reg = ((Lifestyle)Lifestyle.Singleton).CreateRegistration(type, createDelegate, container);
```

**Comment by mkurz01** [comment]
OK, thanks for your fast fix!
